version: "3.8"
services:
  dev:
    build: .
    command: /bin/bash
    depends_on: 
      - db
    stdin_open: true
    tty: true
    volumes:
      - bundle:/usr/local/bundle
      - .:/app:delegated
      - "${HOME}/.gitconfig:/root/.gitconfig"
    working_dir: /app
  app:
    build: .
    depends_on:
      - db
      - webpack-dev-server
    ports: 
      - 3000:3000
    volumes:
      - bundle:/usr/local/bundle
      - .:/app:delegated
    working_dir: /app
  webpack-dev-server:
    build: .
    command: bin/webpack-dev-server
    ports:
      - 3035:3035
    volumes:
      - bundle:/usr/local/bundle
      - .:/app:delegated
    working_dir: /app
  db:
    image: postgres:12.3
    environment: 
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

volumes:
  bundle: