default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lightning_ui_demo
  host: db
  password: password
  username: postgres

test:
  <<: *default
  database: lightning_ui_demo_test
  host: db
  password: password
  username: postgres

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>